# Generated by Django 5.0.3 on 2024-03-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True, verbose_name='company_name')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivery_status_name', models.CharField(max_length=150, unique=True, verbose_name='derivery_status_name')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_office_name', models.CharField(max_length=150, unique=True, verbose_name='Sales_office_name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('role_id', models.IntegerField(verbose_name='role_id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('post_code', models.CharField(max_length=12, null=True, verbose_name='post code')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('sales_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.sales_office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
