# Generated by Django 5.0.3 on 2024-03-20 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandise_name', models.CharField(max_length=150, unique=True, verbose_name='merchandise_name')),
                ('warehouse_address', models.CharField(max_length=150, unique=True, verbose_name='warehouse_address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandise_count', models.IntegerField(verbose_name='merchandise_count')),
                ('delivery_date', models.DateField(verbose_name='delivery_date')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.merchandise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
