# Generated by Django 5.0.3 on 2024-03-17 05:14

from django.db import migrations

def add_company_data(apps, schema_editor):
    Company = apps.get_model('delivery_app','Company')
    company = Company(
        company_name='test_company'
    )
    company.save()

class Migration(migrations.Migration):
    dependencies = [
        ('delivery_app', '0003_company'),
    ]

    operations = [
        migrations.RunPython(add_company_data)
    ]
