# Generated by Django 5.0.3 on 2024-03-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_add_company_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dalivery_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivery_status_name', models.CharField(max_length=150, unique=True, verbose_name='derivery_status_name')),
            ],
        ),
    ]
