# Generated by Django 5.0.3 on 2024-03-20 18:05

from django.db import migrations

def add_user_data(apps, schema_editor):
    User = apps.get_model('delivery_app', 'User')
    user = User(
        password='password1',
        username='testuser',
        role_id=1,
        email='testuser@example.com',
        post_code='1234500',
        address='Test Address',
        is_active=True,
        is_staff=False,
    )
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_add_delivery_status_data'),
    ]

    operations = [
        migrations.RunPython(add_user_data),
    ]
