# Generated by Django 5.0.3 on 2024-03-20 18:46

from django.db import migrations

def add_office_user_data(apps, schema_editor):
    User = apps.get_model('delivery_app', 'User')
    user = User(
        password='password2',
        username='officeuser',
        role_id=2,
        email='officeuser@example.com',
        sales_office_id='1',
        is_active=True,
        is_staff=False,
    )
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0006_add_user_user'),
    ]

    operations = [
        migrations.RunPython(add_office_user_data),
    ]
