# Generated by Django 5.0.3 on 2024-03-17 08:14

from django.db import migrations

def add_driver_data(apps, schema_editor):
    Driver = apps.get_model('delivery_app','Driver')
    driver = Driver(
        drivername = 'YAMADAHAITATU',
        sales_office_id='1',
        role_id='1'
    )
    driver.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0006_add_sales_office_data'),
    ]