# Generated by Django 5.0.3 on 2024-03-20 19:41

from django.db import migrations

def add_driver_user_data(apps, schema_editor):
    User = apps.get_model('delivery_app', 'User')
    user = User(
        password='password3',
        username='driveruser',
        role_id=3,
        email='driveruser@example.com',
        sales_office_id='1',
        is_active=True,
        is_staff=False,
    )
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0007_add_user_office'),
    ]

    operations = [
        migrations.RunPython(add_driver_user_data),
    ]
