# Generated by Django 5.0.3 on 2024-03-17 08:55

from django.db import migrations

def add_merchandise_data(apps, schema_editor):
    Merchandise = apps.get_model('delivery_app','Merchandise')
    merchandise = Merchandise(
        company_id='1',
        merchandise_name = 'Hokkaido',
        warehouse_address = 'test'
    )
    merchandise.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0009_merchandise'),
    ]

    operations = [
        migrations.RunPython(add_merchandise_data)
    ]
