# Generated by Django 5.0.3 on 2024-03-17 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0010_add_merchandise_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandise_count', models.IntegerField(verbose_name='merchandise_count')),
                ('delivery_date', models.DateField(verbose_name='delivery_date')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.merchandise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
