# Generated by Django 5.0.3 on 2024-03-20 19:54

from django.db import migrations

def add_delivery_data(apps, schema_editor):
    Delivery = apps.get_model('delivery_app','Delivery')
    delivery = Delivery(
        user_id='3',
        delivery_status_id = '1',
        order_id = '1',
        delivery_route_no = 'test'
    )
    delivery.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0011_add_order'),
    ]

    operations = [
        migrations.RunPython(add_delivery_data),
    ]
