# Generated by Django 5.0.3 on 2024-03-17 11:29

from django.db import migrations

def add_order_data(apps, schema_editor):
    Order = apps.get_model('delivery_app','Order')
    order = Order(
        user_id='1',
        merchandise_id = '1',
        merchandise_count = '1',
        delivery_date = '2024-3-30'
    )
    order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0011_order'),
    ]

    operations = [
        migrations.RunPython(add_order_data)
    ]
