# Generated by Django 5.0.3 on 2024-03-24 18:15

from django.db import migrations

def add_merchandise_data2(apps, schema_editor):
    Merchandise = apps.get_model('delivery_app','Merchandise')


    merchandise_2 = Merchandise(
        company_id='1',
        merchandise_name = '椅子',
        warehouse_address = 'test2'
    )
    merchandise_3 = Merchandise(
        company_id='1',
        merchandise_name = 'テーブル',
        warehouse_address = 'test3'
    )
    merchandise_4 = Merchandise(
        company_id='1',
        merchandise_name = 'ダイニングテーブル',
        warehouse_address = 'test4'
    )
    merchandise_5 = Merchandise(
        company_id='1',
        merchandise_name = '菓子パン',
        warehouse_address = 'test5'
    )
    merchandise_2.save()
    merchandise_3.save()
    merchandise_4.save()
    merchandise_5.save()


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0012__add_delivery_data'),
    ]

    operations = [
        migrations.RunPython(add_merchandise_data2),
    ]
