# Generated by Django 5.0.3 on 2024-03-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0012_add_order_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_route_no', models.CharField(max_length=200, verbose_name='delivery_route_no')),
                ('delivery_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.delivery_status')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.order')),
            ],
        ),
    ]
