# Generated by Django 5.0.3 on 2024-03-17 12:17

from django.db import migrations

def add_delivery_data(apps, schema_editor):
    Delivery = apps.get_model('delivery_app','Delivery')
    delivery = Delivery(
        driver_id='1',
        delivery_status_id = '1',
        order_id = '1',
        delivery_route_no = 'test'
    )
    delivery.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0013_delivery'),
    ]

    operations = [
        migrations.RunPython(add_delivery_data),
    ]
