# Generated by Django 5.0.3 on 2024-03-26 12:58

from django.db import migrations

def add_user_data(apps, schema_editor):
    User = apps.get_model('delivery_app', 'User')
    user_2 = User(
        password='password4',
        username='testuser2',
        role_id=1,
        email='testuser2@example.com',
        post_code='678910',
        address='Test Address2',
        is_active=True,
        is_staff=False,
    )
    user_3 = User(
        password='password5',
        username='driveruser2',
        role_id=3,
        email='driveruser2@example.com',
        sales_office_id='1',
        is_active=True,
        is_staff=False,
    )
    user_2.save()
    user_3.save()



class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0014_add_order_data'),
    ]

    operations = [
        migrations.RunPython(add_user_data),
    ]
