# Generated by Django 5.0.3 on 2024-03-29 16:40

from django.db import migrations

def add_delivery_data_2(apps, schema_editor):
    Delivery = apps.get_model('delivery_app','Delivery')
    delivery_2 = Delivery(
        user_id='3',
        delivery_status_id = '3',
        order_id = '2',
        delivery_route_no = '1'
    )
    delivery_3 = Delivery(
        user_id='3',
        delivery_status_id = '3',
        order_id = '3',
        delivery_route_no = '1'
    )
    delivery_4 = Delivery(
        user_id='3',
        delivery_status_id = '3',
        order_id = '5',
        delivery_route_no = '1'
    )
    delivery_5 = Delivery(
        user_id='3',
        delivery_status_id = '3',
        order_id = '7',
        delivery_route_no = '1'
    )
    delivery_6 = Delivery(
        user_id='3',
        delivery_status_id = '3',
        order_id = '8',
        delivery_route_no = '1'
    )
    delivery_2.save()
    delivery_3.save()
    delivery_4.save()
    delivery_5.save()
    delivery_6.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0017_add_delivery_status_data'),
    ]

    operations = [
        migrations.RunPython(add_delivery_data_2),
    ]
